name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 3.0.0-rc.17
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  analyzer: ^6.11.0
  collection: ^1.15.0
  gherkin:
    # FIXME This dependency must be removed after the merge of this PR: https://github.com/jonsamwell/dart_gherkin/pull/71
    path: ../dart_gherkin
  source_gen: ^2.0.0
  build: ^2.1.1
  glob: ^2.0.2

dev_dependencies:
  meta: '>=1.7.0 < 2.0.0'
  pedantic: ^1.11.1
  build_config: ^1.0.0
  flutter_lints: ^2.0.1

flutter:
